# GV Robot Pi configuration file

# Movement
DISTANCE = 20
BASE_SPEED = 500
TURNING_SPEED = 150
MIN_SPEED = 25
MAX_SPEED = 50

# Pinout configuration
## Motors
MOTOR_LEFT_PIN = 2
MOTOR_RIGHT_PIN = 3

## Sonic sensors
SONIC_TOP_TRG_PIN = 4
SONIC_TOP_ECH_PIN = 14
SONIC_MDL_TRG_PIN = 17
SONIC_MDL_ECH_PIN = 27
SONIC_BTM_TRG_PIN = 15
SONIC_BTM_ECH_PIN = 18